import { Technology, TechCategory } from "./types";

export const TECH_CATALOG: Record<TechCategory, Technology[]> = {
  "Frontend Frameworks": [
    { id: "react", name: "React", category: "Frontend Frameworks" },
    { id: "nextjs", name: "Next.js", category: "Frontend Frameworks" },
    { id: "vue", name: "Vue", category: "Frontend Frameworks" },
    { id: "nuxt", name: "Nuxt", category: "Frontend Frameworks" },
    { id: "svelte", name: "Svelte", category: "Frontend Frameworks" },
    { id: "angular", name: "Angular", category: "Frontend Frameworks" },
    { id: "remix", name: "Remix", category: "Frontend Frameworks" },
    { id: "astro", name: "Astro", category: "Frontend Frameworks" },
    { id: "solid", name: "SolidJS", category: "Frontend Frameworks" },
    { id: "qwik", name: "Qwik", category: "Frontend Frameworks" },
  ],
  "Backend & Runtimes": [
    { id: "node", name: "Node.js", category: "Backend & Runtimes" },
    { id: "bun", name: "Bun", category: "Backend & Runtimes" },
    { id: "deno", name: "Deno", category: "Backend & Runtimes" },
    { id: "express", name: "Express", category: "Backend & Runtimes" },
    { id: "fastify", name: "Fastify", category: "Backend & Runtimes" },
    { id: "hono", name: "Hono", category: "Backend & Runtimes" },
    { id: "django", name: "Django", category: "Backend & Runtimes" },
    { id: "fastapi", name: "FastAPI", category: "Backend & Runtimes" },
    { id: "go-fiber", name: "Go (Fiber)", category: "Backend & Runtimes" },
    { id: "rust-axum", name: "Rust (Axum)", category: "Backend & Runtimes" },
    { id: "laravel", name: "Laravel", category: "Backend & Runtimes" },
    { id: "rails", name: "Ruby on Rails", category: "Backend & Runtimes" },
  ],
  "Databases (SQL & NoSQL)": [
    { id: "postgres", name: "PostgreSQL", category: "Databases (SQL & NoSQL)" },
    { id: "mysql", name: "MySQL", category: "Databases (SQL & NoSQL)" },
    { id: "mongodb", name: "MongoDB", category: "Databases (SQL & NoSQL)" },
    { id: "sqlite", name: "SQLite", category: "Databases (SQL & NoSQL)" },
    { id: "supabase", name: "Supabase", category: "Databases (SQL & NoSQL)" },
    { id: "planetscale", name: "PlanetScale", category: "Databases (SQL & NoSQL)" },
    { id: "neon", name: "Neon", category: "Databases (SQL & NoSQL)" },
    { id: "redis", name: "Redis", category: "Databases (SQL & NoSQL)" },
    { id: "cassandra", name: "Cassandra", category: "Databases (SQL & NoSQL)" },
    { id: "dynamodb", name: "DynamoDB", category: "Databases (SQL & NoSQL)" },
    { id: "couchdb", name: "CouchDB", category: "Databases (SQL & NoSQL)" },
    { id: "clickhouse", name: "ClickHouse", category: "Databases (SQL & NoSQL)" },
  ],
  "Styling & Design Systems": [
    { id: "tailwind", name: "Tailwind CSS", category: "Styling & Design Systems" },
    { id: "css-modules", name: "CSS Modules", category: "Styling & Design Systems" },
    { id: "styled-components", name: "Styled Components", category: "Styling & Design Systems" },
    { id: "shadcn", name: "shadcn/ui", category: "Styling & Design Systems" },
    { id: "mantine", name: "Mantine", category: "Styling & Design Systems" },
    { id: "chakra", name: "Chakra UI", category: "Styling & Design Systems" },
    { id: "radix", name: "Radix UI", category: "Styling & Design Systems" },
    { id: "daisyui", name: "DaisyUI", category: "Styling & Design Systems" },
    { id: "mui", name: "Material UI", category: "Styling & Design Systems" },
    { id: "antd", name: "Ant Design", category: "Styling & Design Systems" },
  ],
  "Authentication & Identity": [
    { id: "nextauth", name: "NextAuth.js", category: "Authentication & Identity" },
    { id: "clerk", name: "Clerk", category: "Authentication & Identity" },
    { id: "lucia", name: "Lucia Auth", category: "Authentication & Identity" },
    { id: "supabase-auth", name: "Supabase Auth", category: "Authentication & Identity" },
    { id: "firebase-auth", name: "Firebase Auth", category: "Authentication & Identity" },
    { id: "auth0", name: "Auth0", category: "Authentication & Identity" },
    { id: "kinde", name: "Kinde", category: "Authentication & Identity" },
    { id: "better-auth", name: "Better Auth", category: "Authentication & Identity" },
    { id: "passport", name: "Passport.js", category: "Authentication & Identity" },
    { id: "keycloak", name: "Keycloak", category: "Authentication & Identity" },
  ],
  "State Management": [
    { id: "zustand", name: "Zustand", category: "State Management" },
    { id: "redux", name: "Redux Toolkit", category: "State Management" },
    { id: "jotai", name: "Jotai", category: "State Management" },
    { id: "recoil", name: "Recoil", category: "State Management" },
    { id: "mobx", name: "MobX", category: "State Management" },
    { id: "pinia", name: "Pinia", category: "State Management" },
    { id: "xstate", name: "XState", category: "State Management" },
    { id: "tanstack-query", name: "TanStack Query", category: "State Management" },
    { id: "swr", name: "SWR", category: "State Management" },
    { id: "valtio", name: "Valtio", category: "State Management" },
  ],
  "API Architecture & Protocols": [
    { id: "rest", name: "REST", category: "API Architecture & Protocols" },
    { id: "graphql", name: "GraphQL", category: "API Architecture & Protocols" },
    { id: "trpc", name: "tRPC", category: "API Architecture & Protocols" },
    { id: "grpc", name: "gRPC", category: "API Architecture & Protocols" },
    { id: "websocket", name: "WebSocket", category: "API Architecture & Protocols" },
    { id: "sse", name: "Server-Sent Events", category: "API Architecture & Protocols" },
    { id: "openapi", name: "OpenAPI / Swagger", category: "API Architecture & Protocols" },
    { id: "graphql-yoga", name: "GraphQL Yoga", category: "API Architecture & Protocols" },
    { id: "apollo", name: "Apollo", category: "API Architecture & Protocols" },
    { id: "hasura", name: "Hasura", category: "API Architecture & Protocols" },
  ],
  "ORMs & Database Tooling": [
    { id: "prisma", name: "Prisma", category: "ORMs & Database Tooling" },
    { id: "drizzle", name: "Drizzle ORM", category: "ORMs & Database Tooling" },
    { id: "typeorm", name: "TypeORM", category: "ORMs & Database Tooling" },
    { id: "sequelize", name: "Sequelize", category: "ORMs & Database Tooling" },
    { id: "knex", name: "Knex.js", category: "ORMs & Database Tooling" },
    { id: "sqlalchemy", name: "SQLAlchemy", category: "ORMs & Database Tooling" },
    { id: "mongoose", name: "Mongoose", category: "ORMs & Database Tooling" },
    { id: "pg", name: "node-postgres", category: "ORMs & Database Tooling" },
    { id: "elysia-eden", name: "Eden (Elysia)", category: "ORMs & Database Tooling" },
  ],
  "Infrastructure & Deployment": [
    { id: "vercel", name: "Vercel", category: "Infrastructure & Deployment" },
    { id: "netlify", name: "Netlify", category: "Infrastructure & Deployment" },
    { id: "aws", name: "AWS", category: "Infrastructure & Deployment" },
    { id: "cloudflare", name: "Cloudflare", category: "Infrastructure & Deployment" },
    { id: "flyio", name: "Fly.io", category: "Infrastructure & Deployment" },
    { id: "railway", name: "Railway", category: "Infrastructure & Deployment" },
    { id: "render", name: "Render", category: "Infrastructure & Deployment" },
    { id: "digitalocean", name: "DigitalOcean", category: "Infrastructure & Deployment" },
    { id: "kubernetes", name: "Kubernetes", category: "Infrastructure & Deployment" },
    { id: "docker", name: "Docker Compose", category: "Infrastructure & Deployment" },
    { id: "heroku", name: "Heroku", category: "Infrastructure & Deployment" },
  ],
  "Testing & Quality Assurance": [
    { id: "jest", name: "Jest", category: "Testing & Quality Assurance" },
    { id: "vitest", name: "Vitest", category: "Testing & Quality Assurance" },
    { id: "playwright", name: "Playwright", category: "Testing & Quality Assurance" },
    { id: "cypress", name: "Cypress", category: "Testing & Quality Assurance" },
    { id: "testing-library", name: "Testing Library", category: "Testing & Quality Assurance" },
    { id: "mocha", name: "Mocha", category: "Testing & Quality Assurance" },
    { id: "storybook", name: "Storybook", category: "Testing & Quality Assurance" },
    { id: "chromatic", name: "Chromatic", category: "Testing & Quality Assurance" },
    { id: "eslint", name: "ESLint", category: "Testing & Quality Assurance" },
    { id: "prettier", name: "Prettier", category: "Testing & Quality Assurance" },
  ],
  "Package Managers & Build Tools": [
    { id: "npm", name: "npm", category: "Package Managers & Build Tools" },
    { id: "pnpm", name: "pnpm", category: "Package Managers & Build Tools" },
    { id: "yarn", name: "Yarn", category: "Package Managers & Build Tools" },
    { id: "bun-pm", name: "Bun", category: "Package Managers & Build Tools" },
    { id: "vite", name: "Vite", category: "Package Managers & Build Tools" },
    { id: "turbopack", name: "Turbopack", category: "Package Managers & Build Tools" },
    { id: "webpack", name: "Webpack", category: "Package Managers & Build Tools" },
    { id: "esbuild", name: "esbuild", category: "Package Managers & Build Tools" },
    { id: "rollup", name: "Rollup", category: "Package Managers & Build Tools" },
    { id: "turbo", name: "Turborepo", category: "Package Managers & Build Tools" },
  ],
  "CI/CD & DevOps": [
    { id: "github-actions", name: "GitHub Actions", category: "CI/CD & DevOps" },
    { id: "gitlab-ci", name: "GitLab CI", category: "CI/CD & DevOps" },
    { id: "circleci", name: "CircleCI", category: "CI/CD & DevOps" },
    { id: "jenkins", name: "Jenkins", category: "CI/CD & DevOps" },
    { id: "argocd", name: "ArgoCD", category: "CI/CD & DevOps" },
    { id: "terraform", name: "Terraform", category: "CI/CD & DevOps" },
    { id: "ansible", name: "Ansible", category: "CI/CD & DevOps" },
    { id: "pulumi", name: "Pulumi", category: "CI/CD & DevOps" },
    { id: "sst", name: "SST", category: "CI/CD & DevOps" },
  ],
  "Storage & CDN": [
    { id: "s3", name: "Amazon S3", category: "Storage & CDN" },
    { id: "cloudflare-r2", name: "Cloudflare R2", category: "Storage & CDN" },
    { id: "cloudinary", name: "Cloudinary", category: "Storage & CDN" },
    { id: "uploadthing", name: "UploadThing", category: "Storage & CDN" },
    { id: "vercel-blob", name: "Vercel Blob", category: "Storage & CDN" },
    { id: "bunny", name: "Bunny CDN", category: "Storage & CDN" },
    { id: "cloudfront", name: "CloudFront", category: "Storage & CDN" },
    { id: "imgix", name: "Imgix", category: "Storage & CDN" },
  ],
  "Monitoring, Logging & Observability": [
    { id: "sentry", name: "Sentry", category: "Monitoring, Logging & Observability" },
    { id: "datadog", name: "Datadog", category: "Monitoring, Logging & Observability" },
    { id: "grafana", name: "Grafana", category: "Monitoring, Logging & Observability" },
    { id: "prometheus", name: "Prometheus", category: "Monitoring, Logging & Observability" },
    { id: "axiom", name: "Axiom", category: "Monitoring, Logging & Observability" },
    { id: "logtail", name: "Logtail", category: "Monitoring, Logging & Observability" },
    { id: "opentelemetry", name: "OpenTelemetry", category: "Monitoring, Logging & Observability" },
    { id: "pino", name: "Pino", category: "Monitoring, Logging & Observability" },
    { id: "winston", name: "Winston", category: "Monitoring, Logging & Observability" },
  ],
  "Payment & Subscription Processing": [
    { id: "stripe", name: "Stripe", category: "Payment & Subscription Processing" },
    { id: "lemonsqueezy", name: "Lemon Squeezy", category: "Payment & Subscription Processing" },
    { id: "paddle", name: "Paddle", category: "Payment & Subscription Processing" },
    { id: "polar", name: "Polar", category: "Payment & Subscription Processing" },
    { id: "revenuecat", name: "RevenueCat", category: "Payment & Subscription Processing" },
    { id: "braintree", name: "Braintree", category: "Payment & Subscription Processing" },
    { id: "paypal", name: "PayPal", category: "Payment & Subscription Processing" },
    { id: "square", name: "Square", category: "Payment & Subscription Processing" },
  ],
  "Security & Encryption": [
    { id: "arcjet", name: "Arcjet", category: "Security & Encryption" },
    { id: "clerk-security", name: "Clerk (bot detection)", category: "Security & Encryption" },
    { id: "helmet", name: "Helmet.js", category: "Security & Encryption" },
    { id: "owasp-zap", name: "OWASP ZAP", category: "Security & Encryption" },
    { id: "snyk", name: "Snyk", category: "Security & Encryption" },
    { id: "dependabot", name: "Dependabot", category: "Security & Encryption" },
    { id: "hashicorp-vault", name: "HashiCorp Vault", category: "Security & Encryption" },
    { id: "letsencrypt", name: "Let's Encrypt", category: "Security & Encryption" },
  ],
  "Real-time Communication": [
    { id: "socketio", name: "Socket.IO", category: "Real-time Communication" },
    { id: "ws", name: "ws", category: "Real-time Communication" },
    { id: "pusher", name: "Pusher", category: "Real-time Communication" },
    { id: "ably", name: "Ably", category: "Real-time Communication" },
    { id: "liveblocks", name: "Liveblocks", category: "Real-time Communication" },
    { id: "partykit", name: "PartyKit", category: "Real-time Communication" },
    { id: "webrtc", name: "WebRTC", category: "Real-time Communication" },
    { id: "supabase-realtime", name: "Supabase Realtime", category: "Real-time Communication" },
  ],
  "Headless CMS": [
    { id: "strapi", name: "Strapi", category: "Headless CMS" },
    { id: "contentful", name: "Contentful", category: "Headless CMS" },
    { id: "sanity", name: "Sanity", category: "Headless CMS" },
    { id: "payload", name: "Payload CMS", category: "Headless CMS" },
    { id: "keystone", name: "KeystoneJS", category: "Headless CMS" },
    { id: "directus", name: "Directus", category: "Headless CMS" },
    { id: "storyblok", name: "Storyblok", category: "Headless CMS" },
    { id: "prismic", name: "Prismic", category: "Headless CMS" },
  ],
  "Email & Messaging Services": [
    { id: "resend", name: "Resend", category: "Email & Messaging Services" },
    { id: "sendgrid", name: "SendGrid", category: "Email & Messaging Services" },
    { id: "mailgun", name: "Mailgun", category: "Email & Messaging Services" },
    { id: "postmark", name: "Postmark", category: "Email & Messaging Services" },
    { id: "loops", name: "Loops", category: "Email & Messaging Services" },
    { id: "react-email", name: "React Email", category: "Email & Messaging Services" },
    { id: "twilio", name: "Twilio (SMS)", category: "Email & Messaging Services" },
    { id: "novu", name: "Novu", category: "Email & Messaging Services" },
  ],
  "Form Handling & Validation": [
    { id: "react-hook-form", name: "React Hook Form", category: "Form Handling & Validation" },
    { id: "formik", name: "Formik", category: "Form Handling & Validation" },
    { id: "zod", name: "Zod", category: "Form Handling & Validation" },
    { id: "yup", name: "Yup", category: "Form Handling & Validation" },
    { id: "valibot", name: "Valibot", category: "Form Handling & Validation" },
    { id: "conform", name: "Conform", category: "Form Handling & Validation" },
    { id: "tanstack-form", name: "TanStack Form", category: "Form Handling & Validation" },
    { id: "typebox", name: "TypeBox", category: "Form Handling & Validation" },
  ],
  "Analytics & SEO": [
    { id: "vercel-analytics", name: "Vercel Analytics", category: "Analytics & SEO" },
    { id: "google-analytics", name: "Google Analytics", category: "Analytics & SEO" },
    { id: "plausible", name: "Plausible", category: "Analytics & SEO" },
    { id: "posthog", name: "PostHog", category: "Analytics & SEO" },
    { id: "mixpanel", name: "Mixpanel", category: "Analytics & SEO" },
    { id: "next-seo", name: "Next SEO", category: "Analytics & SEO" },
    { id: "unleash", name: "Unleash (feature flags)", category: "Analytics & SEO" },
    { id: "segment", name: "Segment", category: "Analytics & SEO" },
  ],
  "Caching & Performance": [
    { id: "redis-cache", name: "Redis", category: "Caching & Performance" },
    { id: "vercel-kv", name: "Vercel KV", category: "Caching & Performance" },
    { id: "upstash", name: "Upstash", category: "Caching & Performance" },
    { id: "memcached", name: "Memcached", category: "Caching & Performance" },
    { id: "cloudflare-kv", name: "Cloudflare KV", category: "Caching & Performance" },
    { id: "next-cache", name: "Next.js Cache", category: "Caching & Performance" },
    { id: "swr-cache", name: "SWR (stale-while-revalidate)", category: "Caching & Performance" },
    { id: "varnish", name: "Varnish", category: "Caching & Performance" },
  ],
  "Mobile & Cross-Platform Development": [
    { id: "react-native", name: "React Native", category: "Mobile & Cross-Platform Development" },
    { id: "expo", name: "Expo", category: "Mobile & Cross-Platform Development" },
    { id: "flutter", name: "Flutter", category: "Mobile & Cross-Platform Development" },
    { id: "ionic", name: "Ionic", category: "Mobile & Cross-Platform Development" },
    { id: "tauri", name: "Tauri", category: "Mobile & Cross-Platform Development" },
    { id: "electron", name: "Electron", category: "Mobile & Cross-Platform Development" },
    { id: "capacitor", name: "Capacitor", category: "Mobile & Cross-Platform Development" },
    { id: "pwa", name: "PWA", category: "Mobile & Cross-Platform Development" },
  ],
  "Machine Learning & AI Integration": [
    { id: "openai", name: "OpenAI API", category: "Machine Learning & AI Integration" },
    { id: "anthropic", name: "Anthropic Claude", category: "Machine Learning & AI Integration" },
    { id: "langchain", name: "LangChain", category: "Machine Learning & AI Integration" },
    { id: "vercel-ai", name: "Vercel AI SDK", category: "Machine Learning & AI Integration" },
    { id: "huggingface", name: "Hugging Face", category: "Machine Learning & AI Integration" },
    { id: "pinecone", name: "Pinecone", category: "Machine Learning & AI Integration" },
    { id: "chroma", name: "Chroma DB", category: "Machine Learning & AI Integration" },
    { id: "ollama", name: "Ollama", category: "Machine Learning & AI Integration" },
    { id: "replicate", name: "Replicate", category: "Machine Learning & AI Integration" },
  ],
};

export const CATEGORY_ORDER: TechCategory[] = [
  "Frontend Frameworks",
  "Backend & Runtimes",
  "Databases (SQL & NoSQL)",
  "Styling & Design Systems",
  "Authentication & Identity",
  "State Management",
  "API Architecture & Protocols",
  "ORMs & Database Tooling",
  "Infrastructure & Deployment",
  "Testing & Quality Assurance",
  "Package Managers & Build Tools",
  "CI/CD & DevOps",
  "Storage & CDN",
  "Monitoring, Logging & Observability",
  "Payment & Subscription Processing",
  "Security & Encryption",
  "Real-time Communication",
  "Headless CMS",
  "Email & Messaging Services",
  "Form Handling & Validation",
  "Analytics & SEO",
  "Caching & Performance",
  "Mobile & Cross-Platform Development",
  "Machine Learning & AI Integration",
];

export const CATEGORY_LABELS: Record<TechCategory, string> = {
  "Frontend Frameworks": "Frontend Frameworks",
  "Backend & Runtimes": "Backend & Runtimes",
  "Databases (SQL & NoSQL)": "Databases (SQL & NoSQL)",
  "Styling & Design Systems": "Styling & Design Systems",
  "Authentication & Identity": "Authentication & Identity",
  "State Management": "State Management",
  "API Architecture & Protocols": "API Architecture & Protocols",
  "ORMs & Database Tooling": "ORMs & Database Tooling",
  "Infrastructure & Deployment": "Infrastructure & Deployment",
  "Testing & Quality Assurance": "Testing & Quality Assurance",
  "Package Managers & Build Tools": "Package Managers & Build Tools",
  "CI/CD & DevOps": "CI/CD & DevOps",
  "Storage & CDN": "Storage & CDN",
  "Monitoring, Logging & Observability": "Monitoring, Logging & Observability",
  "Payment & Subscription Processing": "Payment & Subscription Processing",
  "Security & Encryption": "Security & Encryption",
  "Real-time Communication": "Real-time Communication",
  "Headless CMS": "Headless CMS",
  "Email & Messaging Services": "Email & Messaging Services",
  "Form Handling & Validation": "Form Handling & Validation",
  "Analytics & SEO": "Analytics & SEO",
  "Caching & Performance": "Caching & Performance",
  "Mobile & Cross-Platform Development": "Mobile & Cross-Platform Development",
  "Machine Learning & AI Integration": "Machine Learning & AI Integration",
};
