import { Technology, TechCategory } from "./types";

import { CostTier } from "./types";

export const TECH_CATALOG: Record<TechCategory, Technology[]> = {
  "Frontend Frameworks": [
    { id: "react", name: "React", category: "Frontend Frameworks" },
    { id: "nextjs", name: "Next.js", category: "Frontend Frameworks" },
    { id: "vue", name: "Vue", category: "Frontend Frameworks" },
    { id: "nuxt", name: "Nuxt", category: "Frontend Frameworks" },
    { id: "svelte", name: "Svelte", category: "Frontend Frameworks" },
    { id: "angular", name: "Angular", category: "Frontend Frameworks" },
    { id: "remix", name: "Remix", category: "Frontend Frameworks" },
    { id: "astro", name: "Astro", category: "Frontend Frameworks" },
    { id: "solid", name: "SolidJS", category: "Frontend Frameworks" },
    { id: "qwik", name: "Qwik", category: "Frontend Frameworks" },
  ],
  "Backend & Runtimes": [
    { id: "node", name: "Node.js", category: "Backend & Runtimes" },
    { id: "bun", name: "Bun", category: "Backend & Runtimes" },
    { id: "deno", name: "Deno", category: "Backend & Runtimes" },
    { id: "express", name: "Express", category: "Backend & Runtimes" },
    { id: "fastify", name: "Fastify", category: "Backend & Runtimes" },
    { id: "hono", name: "Hono", category: "Backend & Runtimes" },
    { id: "django", name: "Django", category: "Backend & Runtimes" },
    { id: "fastapi", name: "FastAPI", category: "Backend & Runtimes" },
    { id: "go-fiber", name: "Go (Fiber)", category: "Backend & Runtimes" },
    { id: "rust-axum", name: "Rust (Axum)", category: "Backend & Runtimes" },
    { id: "laravel", name: "Laravel", category: "Backend & Runtimes" },
    { id: "rails", name: "Ruby on Rails", category: "Backend & Runtimes" },
  ],
  "Databases (SQL & NoSQL)": [
    { id: "postgres", name: "PostgreSQL", category: "Databases (SQL & NoSQL)" },
    { id: "mysql", name: "MySQL", category: "Databases (SQL & NoSQL)" },
    { id: "mongodb", name: "MongoDB", category: "Databases (SQL & NoSQL)" },
    { id: "sqlite", name: "SQLite", category: "Databases (SQL & NoSQL)" },
    { id: "supabase", name: "Supabase", category: "Databases (SQL & NoSQL)" },
    {
      id: "planetscale",
      name: "PlanetScale",
      category: "Databases (SQL & NoSQL)",
    },
    { id: "neon", name: "Neon", category: "Databases (SQL & NoSQL)" },
    { id: "redis", name: "Redis", category: "Databases (SQL & NoSQL)" },
    { id: "cassandra", name: "Cassandra", category: "Databases (SQL & NoSQL)" },
    { id: "dynamodb", name: "DynamoDB", category: "Databases (SQL & NoSQL)" },
    { id: "couchdb", name: "CouchDB", category: "Databases (SQL & NoSQL)" },
    {
      id: "clickhouse",
      name: "ClickHouse",
      category: "Databases (SQL & NoSQL)",
    },
  ],
  "Styling & Design Systems": [
    {
      id: "tailwind",
      name: "Tailwind CSS",
      category: "Styling & Design Systems",
    },
    {
      id: "css-modules",
      name: "CSS Modules",
      category: "Styling & Design Systems",
    },
    {
      id: "styled-components",
      name: "Styled Components",
      category: "Styling & Design Systems",
    },
    { id: "shadcn", name: "shadcn/ui", category: "Styling & Design Systems" },
    { id: "mantine", name: "Mantine", category: "Styling & Design Systems" },
    { id: "chakra", name: "Chakra UI", category: "Styling & Design Systems" },
    { id: "radix", name: "Radix UI", category: "Styling & Design Systems" },
    { id: "daisyui", name: "DaisyUI", category: "Styling & Design Systems" },
    { id: "mui", name: "Material UI", category: "Styling & Design Systems" },
    { id: "antd", name: "Ant Design", category: "Styling & Design Systems" },
  ],
  "Authentication & Identity": [
    {
      id: "nextauth",
      name: "NextAuth.js",
      category: "Authentication & Identity",
    },
    { id: "clerk", name: "Clerk", category: "Authentication & Identity" },
    { id: "lucia", name: "Lucia Auth", category: "Authentication & Identity" },
    {
      id: "supabase-auth",
      name: "Supabase Auth",
      category: "Authentication & Identity",
    },
    {
      id: "firebase-auth",
      name: "Firebase Auth",
      category: "Authentication & Identity",
    },
    { id: "auth0", name: "Auth0", category: "Authentication & Identity" },
    { id: "kinde", name: "Kinde", category: "Authentication & Identity" },
    {
      id: "better-auth",
      name: "Better Auth",
      category: "Authentication & Identity",
    },
    {
      id: "passport",
      name: "Passport.js",
      category: "Authentication & Identity",
    },
    { id: "keycloak", name: "Keycloak", category: "Authentication & Identity" },
  ],
  "State Management": [
    { id: "zustand", name: "Zustand", category: "State Management" },
    { id: "redux", name: "Redux Toolkit", category: "State Management" },
    { id: "jotai", name: "Jotai", category: "State Management" },
    { id: "recoil", name: "Recoil", category: "State Management" },
    { id: "mobx", name: "MobX", category: "State Management" },
    { id: "pinia", name: "Pinia", category: "State Management" },
    { id: "xstate", name: "XState", category: "State Management" },
    {
      id: "tanstack-query",
      name: "TanStack Query",
      category: "State Management",
    },
    { id: "swr", name: "SWR", category: "State Management" },
    { id: "valtio", name: "Valtio", category: "State Management" },
  ],
  "API Architecture & Protocols": [
    { id: "rest", name: "REST", category: "API Architecture & Protocols" },
    {
      id: "graphql",
      name: "GraphQL",
      category: "API Architecture & Protocols",
    },
    { id: "trpc", name: "tRPC", category: "API Architecture & Protocols" },
    { id: "grpc", name: "gRPC", category: "API Architecture & Protocols" },
    {
      id: "websocket",
      name: "WebSocket",
      category: "API Architecture & Protocols",
    },
    {
      id: "sse",
      name: "Server-Sent Events",
      category: "API Architecture & Protocols",
    },
    {
      id: "openapi",
      name: "OpenAPI / Swagger",
      category: "API Architecture & Protocols",
    },
    {
      id: "graphql-yoga",
      name: "GraphQL Yoga",
      category: "API Architecture & Protocols",
    },
    { id: "apollo", name: "Apollo", category: "API Architecture & Protocols" },
    { id: "hasura", name: "Hasura", category: "API Architecture & Protocols" },
  ],
  "ORMs & Database Tooling": [
    { id: "prisma", name: "Prisma", category: "ORMs & Database Tooling" },
    { id: "drizzle", name: "Drizzle ORM", category: "ORMs & Database Tooling" },
    { id: "typeorm", name: "TypeORM", category: "ORMs & Database Tooling" },
    { id: "sequelize", name: "Sequelize", category: "ORMs & Database Tooling" },
    { id: "knex", name: "Knex.js", category: "ORMs & Database Tooling" },
    {
      id: "sqlalchemy",
      name: "SQLAlchemy",
      category: "ORMs & Database Tooling",
    },
    { id: "mongoose", name: "Mongoose", category: "ORMs & Database Tooling" },
    { id: "pg", name: "node-postgres", category: "ORMs & Database Tooling" },
    {
      id: "elysia-eden",
      name: "Eden (Elysia)",
      category: "ORMs & Database Tooling",
    },
  ],
  "Infrastructure & Deployment": [
    { id: "vercel", name: "Vercel", category: "Infrastructure & Deployment" },
    { id: "netlify", name: "Netlify", category: "Infrastructure & Deployment" },
    { id: "aws", name: "AWS", category: "Infrastructure & Deployment" },
    {
      id: "cloudflare",
      name: "Cloudflare",
      category: "Infrastructure & Deployment",
    },
    { id: "flyio", name: "Fly.io", category: "Infrastructure & Deployment" },
    { id: "railway", name: "Railway", category: "Infrastructure & Deployment" },
    { id: "render", name: "Render", category: "Infrastructure & Deployment" },
    {
      id: "digitalocean",
      name: "DigitalOcean",
      category: "Infrastructure & Deployment",
    },
    {
      id: "kubernetes",
      name: "Kubernetes",
      category: "Infrastructure & Deployment",
    },
    {
      id: "docker",
      name: "Docker Compose",
      category: "Infrastructure & Deployment",
    },
    { id: "heroku", name: "Heroku", category: "Infrastructure & Deployment" },
  ],
  "Testing & Quality Assurance": [
    { id: "jest", name: "Jest", category: "Testing & Quality Assurance" },
    { id: "vitest", name: "Vitest", category: "Testing & Quality Assurance" },
    {
      id: "playwright",
      name: "Playwright",
      category: "Testing & Quality Assurance",
    },
    { id: "cypress", name: "Cypress", category: "Testing & Quality Assurance" },
    {
      id: "testing-library",
      name: "Testing Library",
      category: "Testing & Quality Assurance",
    },
    { id: "mocha", name: "Mocha", category: "Testing & Quality Assurance" },
    {
      id: "storybook",
      name: "Storybook",
      category: "Testing & Quality Assurance",
    },
    {
      id: "chromatic",
      name: "Chromatic",
      category: "Testing & Quality Assurance",
    },
    { id: "eslint", name: "ESLint", category: "Testing & Quality Assurance" },
    {
      id: "prettier",
      name: "Prettier",
      category: "Testing & Quality Assurance",
    },
  ],
  "Package Managers & Build Tools": [
    { id: "npm", name: "npm", category: "Package Managers & Build Tools" },
    { id: "pnpm", name: "pnpm", category: "Package Managers & Build Tools" },
    { id: "yarn", name: "Yarn", category: "Package Managers & Build Tools" },
    { id: "bun-pm", name: "Bun", category: "Package Managers & Build Tools" },
    { id: "vite", name: "Vite", category: "Package Managers & Build Tools" },
    {
      id: "turbopack",
      name: "Turbopack",
      category: "Package Managers & Build Tools",
    },
    {
      id: "webpack",
      name: "Webpack",
      category: "Package Managers & Build Tools",
    },
    {
      id: "esbuild",
      name: "esbuild",
      category: "Package Managers & Build Tools",
    },
    {
      id: "rollup",
      name: "Rollup",
      category: "Package Managers & Build Tools",
    },
    {
      id: "turbo",
      name: "Turborepo",
      category: "Package Managers & Build Tools",
    },
  ],
  "CI/CD & DevOps": [
    {
      id: "github-actions",
      name: "GitHub Actions",
      category: "CI/CD & DevOps",
    },
    { id: "gitlab-ci", name: "GitLab CI", category: "CI/CD & DevOps" },
    { id: "circleci", name: "CircleCI", category: "CI/CD & DevOps" },
    { id: "jenkins", name: "Jenkins", category: "CI/CD & DevOps" },
    { id: "argocd", name: "ArgoCD", category: "CI/CD & DevOps" },
    { id: "terraform", name: "Terraform", category: "CI/CD & DevOps" },
    { id: "ansible", name: "Ansible", category: "CI/CD & DevOps" },
    { id: "pulumi", name: "Pulumi", category: "CI/CD & DevOps" },
    { id: "sst", name: "SST", category: "CI/CD & DevOps" },
  ],
  "Storage & CDN": [
    { id: "s3", name: "Amazon S3", category: "Storage & CDN" },
    { id: "cloudflare-r2", name: "Cloudflare R2", category: "Storage & CDN" },
    { id: "cloudinary", name: "Cloudinary", category: "Storage & CDN" },
    { id: "uploadthing", name: "UploadThing", category: "Storage & CDN" },
    { id: "vercel-blob", name: "Vercel Blob", category: "Storage & CDN" },
    { id: "bunny", name: "Bunny CDN", category: "Storage & CDN" },
    { id: "cloudfront", name: "CloudFront", category: "Storage & CDN" },
    { id: "imgix", name: "Imgix", category: "Storage & CDN" },
  ],
  "Monitoring, Logging & Observability": [
    {
      id: "sentry",
      name: "Sentry",
      category: "Monitoring, Logging & Observability",
    },
    {
      id: "datadog",
      name: "Datadog",
      category: "Monitoring, Logging & Observability",
    },
    {
      id: "grafana",
      name: "Grafana",
      category: "Monitoring, Logging & Observability",
    },
    {
      id: "prometheus",
      name: "Prometheus",
      category: "Monitoring, Logging & Observability",
    },
    {
      id: "axiom",
      name: "Axiom",
      category: "Monitoring, Logging & Observability",
    },
    {
      id: "logtail",
      name: "Logtail",
      category: "Monitoring, Logging & Observability",
    },
    {
      id: "opentelemetry",
      name: "OpenTelemetry",
      category: "Monitoring, Logging & Observability",
    },
    {
      id: "pino",
      name: "Pino",
      category: "Monitoring, Logging & Observability",
    },
    {
      id: "winston",
      name: "Winston",
      category: "Monitoring, Logging & Observability",
    },
  ],
  "Payment & Subscription Processing": [
    {
      id: "stripe",
      name: "Stripe",
      category: "Payment & Subscription Processing",
    },
    {
      id: "lemonsqueezy",
      name: "Lemon Squeezy",
      category: "Payment & Subscription Processing",
    },
    {
      id: "paddle",
      name: "Paddle",
      category: "Payment & Subscription Processing",
    },
    {
      id: "polar",
      name: "Polar",
      category: "Payment & Subscription Processing",
    },
    {
      id: "revenuecat",
      name: "RevenueCat",
      category: "Payment & Subscription Processing",
    },
    {
      id: "braintree",
      name: "Braintree",
      category: "Payment & Subscription Processing",
    },
    {
      id: "paypal",
      name: "PayPal",
      category: "Payment & Subscription Processing",
    },
    {
      id: "square",
      name: "Square",
      category: "Payment & Subscription Processing",
    },
  ],
  "Security & Encryption": [
    { id: "arcjet", name: "Arcjet", category: "Security & Encryption" },
    {
      id: "clerk-security",
      name: "Clerk (bot detection)",
      category: "Security & Encryption",
    },
    { id: "helmet", name: "Helmet.js", category: "Security & Encryption" },
    { id: "owasp-zap", name: "OWASP ZAP", category: "Security & Encryption" },
    { id: "snyk", name: "Snyk", category: "Security & Encryption" },
    { id: "dependabot", name: "Dependabot", category: "Security & Encryption" },
    {
      id: "hashicorp-vault",
      name: "HashiCorp Vault",
      category: "Security & Encryption",
    },
    {
      id: "letsencrypt",
      name: "Let's Encrypt",
      category: "Security & Encryption",
    },
  ],
  "Real-time Communication": [
    { id: "socketio", name: "Socket.IO", category: "Real-time Communication" },
    { id: "ws", name: "ws", category: "Real-time Communication" },
    { id: "pusher", name: "Pusher", category: "Real-time Communication" },
    { id: "ably", name: "Ably", category: "Real-time Communication" },
    {
      id: "liveblocks",
      name: "Liveblocks",
      category: "Real-time Communication",
    },
    { id: "partykit", name: "PartyKit", category: "Real-time Communication" },
    { id: "webrtc", name: "WebRTC", category: "Real-time Communication" },
    {
      id: "supabase-realtime",
      name: "Supabase Realtime",
      category: "Real-time Communication",
    },
  ],
  "Headless CMS": [
    { id: "strapi", name: "Strapi", category: "Headless CMS" },
    { id: "contentful", name: "Contentful", category: "Headless CMS" },
    { id: "sanity", name: "Sanity", category: "Headless CMS" },
    { id: "payload", name: "Payload CMS", category: "Headless CMS" },
    { id: "keystone", name: "KeystoneJS", category: "Headless CMS" },
    { id: "directus", name: "Directus", category: "Headless CMS" },
    { id: "storyblok", name: "Storyblok", category: "Headless CMS" },
    { id: "prismic", name: "Prismic", category: "Headless CMS" },
  ],
  "Email & Messaging Services": [
    { id: "resend", name: "Resend", category: "Email & Messaging Services" },
    {
      id: "sendgrid",
      name: "SendGrid",
      category: "Email & Messaging Services",
    },
    { id: "mailgun", name: "Mailgun", category: "Email & Messaging Services" },
    {
      id: "postmark",
      name: "Postmark",
      category: "Email & Messaging Services",
    },
    { id: "loops", name: "Loops", category: "Email & Messaging Services" },
    {
      id: "react-email",
      name: "React Email",
      category: "Email & Messaging Services",
    },
    {
      id: "twilio",
      name: "Twilio (SMS)",
      category: "Email & Messaging Services",
    },
    { id: "novu", name: "Novu", category: "Email & Messaging Services" },
  ],
  "Form Handling & Validation": [
    {
      id: "react-hook-form",
      name: "React Hook Form",
      category: "Form Handling & Validation",
    },
    { id: "formik", name: "Formik", category: "Form Handling & Validation" },
    { id: "zod", name: "Zod", category: "Form Handling & Validation" },
    { id: "yup", name: "Yup", category: "Form Handling & Validation" },
    { id: "valibot", name: "Valibot", category: "Form Handling & Validation" },
    { id: "conform", name: "Conform", category: "Form Handling & Validation" },
    {
      id: "tanstack-form",
      name: "TanStack Form",
      category: "Form Handling & Validation",
    },
    { id: "typebox", name: "TypeBox", category: "Form Handling & Validation" },
  ],
  "Analytics & SEO": [
    {
      id: "vercel-analytics",
      name: "Vercel Analytics",
      category: "Analytics & SEO",
    },
    {
      id: "google-analytics",
      name: "Google Analytics",
      category: "Analytics & SEO",
    },
    { id: "plausible", name: "Plausible", category: "Analytics & SEO" },
    { id: "posthog", name: "PostHog", category: "Analytics & SEO" },
    { id: "mixpanel", name: "Mixpanel", category: "Analytics & SEO" },
    { id: "next-seo", name: "Next SEO", category: "Analytics & SEO" },
    {
      id: "unleash",
      name: "Unleash (feature flags)",
      category: "Analytics & SEO",
    },
    { id: "segment", name: "Segment", category: "Analytics & SEO" },
  ],
  "Caching & Performance": [
    { id: "redis-cache", name: "Redis", category: "Caching & Performance" },
    { id: "vercel-kv", name: "Vercel KV", category: "Caching & Performance" },
    { id: "upstash", name: "Upstash", category: "Caching & Performance" },
    { id: "memcached", name: "Memcached", category: "Caching & Performance" },
    {
      id: "cloudflare-kv",
      name: "Cloudflare KV",
      category: "Caching & Performance",
    },
    {
      id: "next-cache",
      name: "Next.js Cache",
      category: "Caching & Performance",
    },
    {
      id: "swr-cache",
      name: "SWR (stale-while-revalidate)",
      category: "Caching & Performance",
    },
    { id: "varnish", name: "Varnish", category: "Caching & Performance" },
  ],
  "Mobile & Cross-Platform Development": [
    {
      id: "react-native",
      name: "React Native",
      category: "Mobile & Cross-Platform Development",
    },
    {
      id: "expo",
      name: "Expo",
      category: "Mobile & Cross-Platform Development",
    },
    {
      id: "flutter",
      name: "Flutter",
      category: "Mobile & Cross-Platform Development",
    },
    {
      id: "ionic",
      name: "Ionic",
      category: "Mobile & Cross-Platform Development",
    },
    {
      id: "tauri",
      name: "Tauri",
      category: "Mobile & Cross-Platform Development",
    },
    {
      id: "electron",
      name: "Electron",
      category: "Mobile & Cross-Platform Development",
    },
    {
      id: "capacitor",
      name: "Capacitor",
      category: "Mobile & Cross-Platform Development",
    },
    { id: "pwa", name: "PWA", category: "Mobile & Cross-Platform Development" },
  ],
  "Machine Learning & AI Integration": [
    {
      id: "openai",
      name: "OpenAI API",
      category: "Machine Learning & AI Integration",
    },
    {
      id: "anthropic",
      name: "Anthropic Claude",
      category: "Machine Learning & AI Integration",
    },
    {
      id: "langchain",
      name: "LangChain",
      category: "Machine Learning & AI Integration",
    },
    {
      id: "vercel-ai",
      name: "Vercel AI SDK",
      category: "Machine Learning & AI Integration",
    },
    {
      id: "huggingface",
      name: "Hugging Face",
      category: "Machine Learning & AI Integration",
    },
    {
      id: "pinecone",
      name: "Pinecone",
      category: "Machine Learning & AI Integration",
    },
    {
      id: "chroma",
      name: "Chroma DB",
      category: "Machine Learning & AI Integration",
    },
    {
      id: "ollama",
      name: "Ollama",
      category: "Machine Learning & AI Integration",
    },
    {
      id: "replicate",
      name: "Replicate",
      category: "Machine Learning & AI Integration",
    },
  ],
};

export const CATEGORY_ORDER: TechCategory[] = [
  "Frontend Frameworks",
  "Backend & Runtimes",
  "Databases (SQL & NoSQL)",
  "Styling & Design Systems",
  "Authentication & Identity",
  "State Management",
  "API Architecture & Protocols",
  "ORMs & Database Tooling",
  "Infrastructure & Deployment",
  "Testing & Quality Assurance",
  "Package Managers & Build Tools",
  "CI/CD & DevOps",
  "Storage & CDN",
  "Monitoring, Logging & Observability",
  "Payment & Subscription Processing",
  "Security & Encryption",
  "Real-time Communication",
  "Headless CMS",
  "Email & Messaging Services",
  "Form Handling & Validation",
  "Analytics & SEO",
  "Caching & Performance",
  "Mobile & Cross-Platform Development",
  "Machine Learning & AI Integration",
];

export const CATEGORY_LABELS: Record<TechCategory, string> = {
  "Frontend Frameworks": "Frontend Frameworks",
  "Backend & Runtimes": "Backend & Runtimes",
  "Databases (SQL & NoSQL)": "Databases (SQL & NoSQL)",
  "Styling & Design Systems": "Styling & Design Systems",
  "Authentication & Identity": "Authentication & Identity",
  "State Management": "State Management",
  "API Architecture & Protocols": "API Architecture & Protocols",
  "ORMs & Database Tooling": "ORMs & Database Tooling",
  "Infrastructure & Deployment": "Infrastructure & Deployment",
  "Testing & Quality Assurance": "Testing & Quality Assurance",
  "Package Managers & Build Tools": "Package Managers & Build Tools",
  "CI/CD & DevOps": "CI/CD & DevOps",
  "Storage & CDN": "Storage & CDN",
  "Monitoring, Logging & Observability": "Monitoring, Logging & Observability",
  "Payment & Subscription Processing": "Payment & Subscription Processing",
  "Security & Encryption": "Security & Encryption",
  "Real-time Communication": "Real-time Communication",
  "Headless CMS": "Headless CMS",
  "Email & Messaging Services": "Email & Messaging Services",
  "Form Handling & Validation": "Form Handling & Validation",
  "Analytics & SEO": "Analytics & SEO",
  "Caching & Performance": "Caching & Performance",
  "Mobile & Cross-Platform Development": "Mobile & Cross-Platform Development",
  "Machine Learning & AI Integration": "Machine Learning & AI Integration",
};

/**
 * Estimated monthly cost per technology at production scale (startup team).
 * Ranges account for free tiers, pay-as-you-go, and team plans.
 */
export const COST_ESTIMATES: Record<string, { tier: CostTier; range: string }> =
  {
    // Frontend Frameworks
    react: { tier: "free", range: "$0" },
    nextjs: { tier: "free", range: "$0" },
    vue: { tier: "free", range: "$0" },
    nuxt: { tier: "free", range: "$0" },
    svelte: { tier: "free", range: "$0" },
    angular: { tier: "free", range: "$0" },
    remix: { tier: "free", range: "$0" },
    astro: { tier: "free", range: "$0" },
    solid: { tier: "free", range: "$0" },
    qwik: { tier: "free", range: "$0" },

    // Backend & Runtimes
    node: { tier: "free", range: "$0" },
    bun: { tier: "free", range: "$0" },
    deno: { tier: "free", range: "$0" },
    express: { tier: "free", range: "$0" },
    fastify: { tier: "free", range: "$0" },
    hono: { tier: "free", range: "$0" },
    django: { tier: "free", range: "$0" },
    fastapi: { tier: "free", range: "$0" },
    "go-fiber": { tier: "free", range: "$0" },
    "rust-axum": { tier: "free", range: "$0" },
    laravel: { tier: "free", range: "$0" },
    rails: { tier: "free", range: "$0" },

    // Databases
    postgres: { tier: "low", range: "$0-$50" },
    mysql: { tier: "low", range: "$0-$50" },
    mongodb: { tier: "medium", range: "$0-$120" },
    sqlite: { tier: "free", range: "$0" },
    supabase: { tier: "low", range: "$0-$75" },
    planetscale: { tier: "medium", range: "$29-$299" },
    neon: { tier: "low", range: "$0-$80" },
    redis: { tier: "low", range: "$0-$60" },
    cassandra: { tier: "high", range: "$100-$500" },
    dynamodb: { tier: "medium", range: "$0-$200" },
    couchdb: { tier: "low", range: "$0-$50" },
    clickhouse: { tier: "high", range: "$80-$600" },

    // Styling
    tailwind: { tier: "free", range: "$0" },
    "css-modules": { tier: "free", range: "$0" },
    "styled-components": { tier: "free", range: "$0" },
    shadcn: { tier: "free", range: "$0" },
    mantine: { tier: "free", range: "$0" },
    chakra: { tier: "free", range: "$0" },
    radix: { tier: "free", range: "$0" },
    daisyui: { tier: "free", range: "$0" },
    mui: { tier: "free", range: "$0" },
    antd: { tier: "free", range: "$0" },

    // Auth
    nextauth: { tier: "free", range: "$0" },
    clerk: { tier: "low", range: "$0–$99" },
    lucia: { tier: "free", range: "$0" },
    "supabase-auth": { tier: "free", range: "$0" },
    "firebase-auth": { tier: "free", range: "$0" },
    auth0: { tier: "medium", range: "$0–$240" },
    kinde: { tier: "low", range: "$0–$90" },
    "better-auth": { tier: "free", range: "$0" },
    passport: { tier: "free", range: "$0" },
    keycloak: { tier: "free", range: "$0" },

    // State Management
    zustand: { tier: "free", range: "$0" },
    redux: { tier: "free", range: "$0" },
    jotai: { tier: "free", range: "$0" },
    recoil: { tier: "free", range: "$0" },
    mobx: { tier: "free", range: "$0" },
    pinia: { tier: "free", range: "$0" },
    xstate: { tier: "free", range: "$0" },
    "tanstack-query": { tier: "free", range: "$0" },
    swr: { tier: "free", range: "$0" },
    valtio: { tier: "free", range: "$0" },

    // API
    rest: { tier: "free", range: "$0" },
    graphql: { tier: "free", range: "$0" },
    trpc: { tier: "free", range: "$0" },
    grpc: { tier: "free", range: "$0" },
    websocket: { tier: "free", range: "$0" },
    sse: { tier: "free", range: "$0" },
    openapi: { tier: "free", range: "$0" },
    "graphql-yoga": { tier: "free", range: "$0" },
    apollo: { tier: "low", range: "$0–$99" },
    hasura: { tier: "medium", range: "$0–$150" },

    // ORMs
    prisma: { tier: "free", range: "$0" },
    drizzle: { tier: "free", range: "$0" },
    typeorm: { tier: "free", range: "$0" },
    sequelize: { tier: "free", range: "$0" },
    knex: { tier: "free", range: "$0" },
    sqlalchemy: { tier: "free", range: "$0" },
    mongoose: { tier: "free", range: "$0" },
    pg: { tier: "free", range: "$0" },
    "elysia-eden": { tier: "free", range: "$0" },

    // Infrastructure
    vercel: { tier: "low", range: "$0-$55" },
    netlify: { tier: "low", range: "$0-$45" },
    aws: { tier: "high", range: "$30-$500" },
    cloudflare: { tier: "low", range: "$0-$50" },
    flyio: { tier: "low", range: "$0-$60" },
    railway: { tier: "low", range: "$5-$80" },
    render: { tier: "low", range: "$0-$85" },
    digitalocean: { tier: "medium", range: "$6-$200" },
    kubernetes: { tier: "high", range: "$100-$800" },
    docker: { tier: "free", range: "$0" },
    heroku: { tier: "medium", range: "$7-$250" },

    // Testing
    jest: { tier: "free", range: "$0" },
    vitest: { tier: "free", range: "$0" },
    playwright: { tier: "free", range: "$0" },
    cypress: { tier: "low", range: "$0-$75" },
    "testing-library": { tier: "free", range: "$0" },
    mocha: { tier: "free", range: "$0" },
    storybook: { tier: "free", range: "$0" },
    chromatic: { tier: "low", range: "$0-$149" },
    eslint: { tier: "free", range: "$0" },
    prettier: { tier: "free", range: "$0" },

    // Package Managers
    npm: { tier: "free", range: "$0" },
    pnpm: { tier: "free", range: "$0" },
    yarn: { tier: "free", range: "$0" },
    "bun-pm": { tier: "free", range: "$0" },
    vite: { tier: "free", range: "$0" },
    turbopack: { tier: "free", range: "$0" },
    webpack: { tier: "free", range: "$0" },
    esbuild: { tier: "free", range: "$0" },
    rollup: { tier: "free", range: "$0" },
    turbo: { tier: "free", range: "$0" },

    // CI/CD
    "github-actions": { tier: "low", range: "$0-$40" },
    "gitlab-ci": { tier: "low", range: "$0-$40" },
    circleci: { tier: "medium", range: "$0-$120" },
    jenkins: { tier: "medium", range: "$0-$150" },
    argocd: { tier: "free", range: "$0" },
    terraform: { tier: "low", range: "$0-$80" },
    ansible: { tier: "free", range: "$0" },
    pulumi: { tier: "low", range: "$0-$60" },
    sst: { tier: "free", range: "$0" },

    // Storage & CDN
    s3: { tier: "low", range: "$1-$50" },
    "cloudflare-r2": { tier: "low", range: "$0-$20" },
    cloudinary: { tier: "medium", range: "$0-$150" },
    uploadthing: { tier: "low", range: "$0-$25" },
    "vercel-blob": { tier: "low", range: "$0-$30" },
    bunny: { tier: "low", range: "$1-$40" },
    cloudfront: { tier: "low", range: "$0-$40" },
    imgix: { tier: "medium", range: "$0-$100" },

    // Monitoring
    sentry: { tier: "low", range: "$0-$90" },
    datadog: { tier: "high", range: "$0-$500" },
    grafana: { tier: "medium", range: "$0-$150" },
    prometheus: { tier: "free", range: "$0" },
    axiom: { tier: "medium", range: "$0-$250" },
    logtail: { tier: "low", range: "$0-$60" },
    opentelemetry: { tier: "free", range: "$0" },
    pino: { tier: "free", range: "$0" },
    winston: { tier: "free", range: "$0" },

    // Payments
    stripe: { tier: "low", range: "$0 + 2.9% + $0.30/txn" },
    lemonsqueezy: { tier: "low", range: "$0 + 5% + $0.50/txn" },
    paddle: { tier: "low", range: "$0 + 5% + $0.50/txn" },
    polar: { tier: "low", range: "$0 + 5%" },
    revenuecat: { tier: "medium", range: "$0-$200" },
    braintree: { tier: "low", range: "$0 + 2.59% + $0.49/txn" },
    paypal: { tier: "free", range: "$0 + 2.9% + $0.30/txn" },
    square: { tier: "free", range: "$0 + 2.6% + $0.10/txn" },

    // Security
    arcjet: { tier: "low", range: "$0-$40" },
    "clerk-security": { tier: "low", range: "$0-$99" },
    helmet: { tier: "free", range: "$0" },
    "owasp-zap": { tier: "free", range: "$0" },
    snyk: { tier: "medium", range: "$0-$200" },
    dependabot: { tier: "free", range: "$0" },
    "hashicorp-vault": { tier: "medium", range: "$0-$200" },
    letsencrypt: { tier: "free", range: "$0" },

    // Real-time
    socketio: { tier: "free", range: "$0" },
    ws: { tier: "free", range: "$0" },
    pusher: { tier: "medium", range: "$0-$150" },
    ably: { tier: "medium", range: "$0-$150" },
    liveblocks: { tier: "medium", range: "$0-$199" },
    partykit: { tier: "low", range: "$0-$49" },
    webrtc: { tier: "free", range: "$0" },
    "supabase-realtime": { tier: "free", range: "$0" },

    // Headless CMS
    strapi: { tier: "free", range: "$0" },
    contentful: { tier: "medium", range: "$0-$489" },
    sanity: { tier: "low", range: "$0-$99" },
    payload: { tier: "free", range: "$0" },
    keystone: { tier: "free", range: "$0" },
    directus: { tier: "free", range: "$0" },
    storyblok: { tier: "medium", range: "$0-$120" },
    prismic: { tier: "low", range: "$0-$100" },

    // Email
    resend: { tier: "low", range: "$0-$35" },
    sendgrid: { tier: "low", range: "$0-$90" },
    mailgun: { tier: "low", range: "$0-$100" },
    postmark: { tier: "low", range: "$0-$50" },
    loops: { tier: "low", range: "$0-$50" },
    "react-email": { tier: "free", range: "$0" },
    twilio: { tier: "medium", range: "$0 + per SMS" },
    novu: { tier: "low", range: "$0-$60" },

    // Forms
    "react-hook-form": { tier: "free", range: "$0" },
    formik: { tier: "free", range: "$0" },
    zod: { tier: "free", range: "$0" },
    yup: { tier: "free", range: "$0" },
    valibot: { tier: "free", range: "$0" },
    conform: { tier: "free", range: "$0" },
    "tanstack-form": { tier: "free", range: "$0" },
    typebox: { tier: "free", range: "$0" },

    // Analytics
    "vercel-analytics": { tier: "low", range: "$0-$16" },
    "google-analytics": { tier: "free", range: "$0" },
    plausible: { tier: "low", range: "$9-$30" },
    posthog: { tier: "low", range: "$0-$250" },
    mixpanel: { tier: "medium", range: "$0-$200" },
    "next-seo": { tier: "free", range: "$0" },
    unleash: { tier: "low", range: "$0-$80" },
    segment: { tier: "medium", range: "$0-$250" },

    // Caching
    "redis-cache": { tier: "low", range: "$0-$60" },
    "vercel-kv": { tier: "low", range: "$0-$30" },
    upstash: { tier: "low", range: "$0-$60" },
    memcached: { tier: "low", range: "$0-$40" },
    "cloudflare-kv": { tier: "low", range: "$0-$15" },
    "next-cache": { tier: "free", range: "$0" },
    "swr-cache": { tier: "free", range: "$0" },
    varnish: { tier: "free", range: "$0" },

    // Mobile
    "react-native": { tier: "free", range: "$0" },
    expo: { tier: "medium", range: "$0-$200" },
    flutter: { tier: "free", range: "$0" },
    ionic: { tier: "medium", range: "$0-$100" },
    tauri: { tier: "free", range: "$0" },
    electron: { tier: "free", range: "$0" },
    capacitor: { tier: "free", range: "$0" },
    pwa: { tier: "free", range: "$0" },

    // AI/ML
    openai: { tier: "high", range: "$5-$1,000" },
    anthropic: { tier: "high", range: "$5-$500" },
    langchain: { tier: "free", range: "$0" },
    "vercel-ai": { tier: "free", range: "$0" },
    huggingface: { tier: "medium", range: "$0-$300" },
    pinecone: { tier: "medium", range: "$0-$200" },
    chroma: { tier: "free", range: "$0" },
    ollama: { tier: "free", range: "$0" },
    replicate: { tier: "medium", range: "$0-$200" },
  };
